name: Deploy Website to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: yarn install
      - run: yarn build

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SELF_SERVER_IP }} # Your home server IP or hostname
          username: ${{ secrets.SELF_SERVER_SSH_USERNAME }} # Your SSH username
          key: ${{ secrets.SELF_SERVER_SSH_PRIVATE_KEY }} # Your SSH private key
          port: ${{ secrets.SELF_SERVER_SSH_PORT }} # Your SSH port
          source: './build/*' # Source path of the built files
          target: '/home/edd/edd-williams/' # Target path on your server
