name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Copy files to local server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SELF_SERVER_SSH_USERNAME }}
          SSH_PORT: ${{ secrets.SELF_SERVER_SSH_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SELF_SERVER_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SELF_SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -P $SSH_PORT -i ~/.ssh/id_rsa -r ./build/* $SSH_USERNAME@$SERVER_IP:/home/edd/shared-apps/
